name: Feature Request
description: Give us an idea for our ancient mod!
labels: ["feature"]
body:
  - type: textarea
    id: describe-feature
    attributes:
      label: Describe your feature!
      description: What do you want in archaeology mod? 
      placeholder: Describe your new feature here
    validations:
      required: true
  - type: textarea
    id: mda
    attributes:
      label: Media
      description: If you has an textures for feature or screenshots, you can send them here.
